[build]
  Functions = "functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/show-and-tell"
  status = 302

[[redirects]]
  from = "/where"
  to = "https://rga.com"
  status = 200
